# -*- coding: utf-8 -*-
"""project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uM4dBYMsbl95COUfqOYxtyDWD7lX96QX
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

df = pd.read_csv('/content/Crop_recommendationV2.csv')
df.info()
df.head()

print(df.isnull().sum())

X = df.drop(columns=['label'])
y = df['label']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_train

knn = KNeighborsClassifier(n_neighbors=5, metric='euclidean')

knn.fit(X_train, y_train)

# Predict on the test set
y_pred = knn.predict(X_test)

# Display predictions
y_pred

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print(cm)

# Evaluate model performance
accuracy = accuracy_score(y_test, y_pred)
print(f"\nModel Accuracy: {accuracy:.2f}")

print(classification_report(y_test, y_pred))

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report

# Generate classification report as a dictionary
class_report_dict = classification_report(y_test, y_pred, output_dict=True)

# Convert classification report to DataFrame
class_report_df = pd.DataFrame(class_report_dict).transpose()

# Display the dataframe
print(class_report_df)

import matplotlib.pyplot as plt
import seaborn as sns

# Generate heatmap for classification report
plt.figure(figsize=(8,5))

sns.heatmap(class_report_df.iloc[:-1, :-1],
            annot=True,
            cmap="YlGnBu",
            linewidths=0.5)

plt.title("Classification Report Heatmap")
plt.show()

# predicting using custom input
sample = [[90, 40, 40, 25, 80, 6.5, 200, 30, 2, 8, 5, 400, 3, 2, 10, 1, 5, 2, 0, 1, 0, 75]]

pred = knn.predict(sample)

print("Predicted Crop:", pred)

# predicting using custom input
sample = [[90, 42, 43, 25.5, 80.2, 6.5, 202.0,
           30, 2, 8, 5, 400, 3, 2, 10, 1, 5, 2, 0, 1, 0, 75]]

sample_scaled = scaler.transform(sample)

pred = knn.predict(sample_scaled)

print("Predicted Crop:", pred)